### PR TITLE
RFC: chrome.bluetooth: implement lowEnergy for Android

### PR DESCRIPTION
**Pull request by bpowers**
Please consider this a rough-draft/RFC level pull request.  I've implemented what I need for now for access to a device I'm working with, and it appears to working/stable.  This includes:

- LE connection
- gatt service enumeration
- characteristic enumeration
- write characteristic
- characteristic notifications

What is the best way to get this upstreamed?  Should I break the pull requests up?  Should I finish up the rest of the implementation (`disconnect`, getDescriptor`, `readCharacteristicValue`, `stopCharacteristicNotifications`, `onServiceRemoved`, `onDescriptorValueChanged` I think are the big missing ones) first?  Does the code look generally agreeable?  I've tried to crib from the iOS side of this plugin, while matching this coding style as much as possible.

So, guidance + critiques welcome.

### CODE REVIEW

**Comment by mmocny** [comment]
Thanks again for contributions, but I'm a bit confused, have you seen our [bluetoothLowEnergy plugin?](https://github.com/MobileChromeApps/mobile-chrome-apps/tree/master/chrome-cordova/plugins/chrome.bluetoothLowEnergy)

If that plugin is missing functionality, I think any additions you add belong there.  Let me know if I misunderstand, then I will take a look.

**Comment by bpowers** [comment]
huh, it does seem like I'm the one confused here.  I think what happened, perhaps, is that I did `cca plugin add org.chromium.bluetoothLowEnergy`, and it looks like I got an old version that didn't have a source directory.  Damn :)  I'll switch to the latest code and verify things are working as intended.

**Comment by bpowers** [comment]
For the record, the reason I took this approach (clobbering bluetooth) is because that seems to be how the iOS side of things works.  I assumed there was a reason for that.

**Comment by mmocny** [comment]
So you've got the old source because we have not updated the latest plugin versions to the cordova plugin registry.  Andrew tried to do that last week, but there is a problem with the registry at the moment.

For iOS, I think the reason Rui (an intern from last term) took that approach was because the implementation was far more tightly coupled, and it was just impractical to split out.

**Comment by bpowers** [comment]
got it - makes sense about the coupling.

Going to close this, the code on master seems to generally be working for me.  Thanks!

**Pull request closed without merging**
